from lex import Errors as E, Generic as G, Keywords as K, Literals as L, Operators as O, Symbols as S

EPSILON = None

IGNORED_TOKENS = {G.BLOCK_CMT, G.INLINE_CMT, E.DANGLING_BLOCK_COMMENT, E.INVALID_CHARACTER, E.INVALID_IDENTIFIER, E.INVALID_NUMBER}

FIRST_statement = {K.WRITE, K.RETURN, G.ID, K.IF, K.READ, K.WHILE}
FIRST_rept_opt_class_decl22 = {S.COMMA, EPSILON}
FIRST_rept_indice = {S.OPEN_SBR, EPSILON}
FIRST_rept_function_call0 = {G.ID, EPSILON}
FIRST_add_op = {O.OR, O.PLUS, O.MINUS}
FIRST_rept_opt_func_body01 = {G.ID, EPSILON, K.INTEGER, K.FLOAT}
FIRST_visibility = {K.PUBLIC, K.PRIVATE}
FIRST_START = {G.ID, K.MAIN, K.CLASS}
FIRST_func_head = {G.ID}
FIRST_func_def = {G.ID}
FIRST_a_params_tail = {S.COMMA}
FIRST_func_decl = {G.ID}
FIRST_var_decl = {G.ID, K.INTEGER, K.FLOAT}
FIRST_f_params_tail = {S.COMMA}
FIRST_member_decl = {G.ID, K.INTEGER, K.FLOAT}
FIRST_a_params = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, EPSILON, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FIRST_class_decl = {K.CLASS}
FIRST_f_params = {G.ID, EPSILON, K.INTEGER, K.FLOAT}
FIRST_rel_op = {O.LTE, O.GT, O.NEQ, O.LT, O.EQ, O.GTE}
FIRST_indice = {S.OPEN_SBR}
FIRST_func_body = {K.LOCAL, K.DO}
FIRST_opt_func_head0 = {G.ID, EPSILON}
FIRST_sign = {O.PLUS, O.MINUS}
FIRST_stat_block = {K.WRITE, K.RETURN, G.ID, K.IF, EPSILON, K.DO, K.READ, K.WHILE}
FIRST_rel_expr = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FIRST_variable = {G.ID}
FIRST_factor = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FIRST_prog = {G.ID, K.MAIN, K.CLASS}
FIRST_term = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FIRST_mult_op = {O.MULT, O.AND, O.DIV}
FIRST_rightrec_term = {O.MULT, O.AND, EPSILON, O.DIV}
FIRST_rept_var_decl2 = {S.OPEN_SBR, EPSILON}
FIRST_opt_class_decl2 = {K.INHERITS, EPSILON}
FIRST_rept_a_params1 = {S.COMMA, EPSILON}
FIRST_expr = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FIRST_idnest = {G.ID}
FIRST_rept_f_params_tail3 = {S.OPEN_SBR, EPSILON}
FIRST_function_call = {G.ID}
FIRST_rept_class_decl4 = {K.PUBLIC, EPSILON, K.PRIVATE}
FIRST_type = {G.ID, K.INTEGER, K.FLOAT}
FIRST_arith_expr = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FIRST_rept_f_params2 = {S.OPEN_SBR, EPSILON}
FIRST_rightrec_arith_expr = {O.OR, O.PLUS, EPSILON, O.MINUS}
FIRST_rept_f_params3 = {S.COMMA, EPSILON}
FIRST_array_size = {S.OPEN_SBR}
FIRST_assign_stat = {G.ID}
FIRST_opt_func_body0 = {K.LOCAL, EPSILON}
FIRST_rept_func_body2 = {K.WRITE, K.RETURN, G.ID, K.IF, EPSILON, K.READ, K.WHILE}
FIRST_rept_stat_block1 = {K.WRITE, K.RETURN, G.ID, K.IF, EPSILON, K.READ, K.WHILE}
FIRST_rept_variable0 = {G.ID, EPSILON}
FIRST_rept_prog0 = {EPSILON, K.CLASS}
FIRST_rept_variable2 = {S.OPEN_SBR, EPSILON}
FIRST_rept_prog1 = {G.ID, EPSILON}

FOLLOW_statement = {K.WRITE, K.RETURN, K.ELSE, G.ID, S.SEMI_COLON, K.IF, K.END, K.READ, K.WHILE}
FOLLOW_rept_opt_class_decl22 = {S.OPEN_CBR}
FOLLOW_rept_indice = {S.DOT, O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.ASSIGN, S.CLOSE_PAR, O.MULT, O.AND, O.PLUS, S.COMMA, O.MINUS, O.DIV, O.EQ, O.GTE}
FOLLOW_rept_function_call0 = {G.ID}
FOLLOW_add_op = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FOLLOW_rept_opt_func_body01 = {K.DO}
FOLLOW_visibility = {G.ID, K.INTEGER, K.FLOAT}
FOLLOW_START = {G.EOF}
FOLLOW_func_head = {K.LOCAL, K.DO}
FOLLOW_func_def = {G.ID, K.MAIN}
FOLLOW_a_params_tail = {S.CLOSE_PAR, S.COMMA}
FOLLOW_func_decl = {K.PUBLIC, S.CLOSE_CBR, K.PRIVATE}
FOLLOW_var_decl = {K.PUBLIC, G.ID, S.CLOSE_CBR, K.DO, K.PRIVATE, K.INTEGER, K.FLOAT}
FOLLOW_f_params_tail = {S.CLOSE_PAR, S.COMMA}
FOLLOW_member_decl = {K.PUBLIC, S.CLOSE_CBR, K.PRIVATE}
FOLLOW_a_params = {S.CLOSE_PAR}
FOLLOW_class_decl = {G.ID, K.MAIN, K.CLASS}
FOLLOW_f_params = {S.CLOSE_PAR}
FOLLOW_rel_op = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FOLLOW_indice = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.OPEN_SBR, S.SEMI_COLON, S.CLOSE_SBR, S.ASSIGN, S.CLOSE_PAR, O.MULT, O.AND, O.PLUS, S.COMMA, O.MINUS, S.DOT, O.DIV, O.EQ, O.GTE}
FOLLOW_func_body = {G.EOF, S.SEMI_COLON}
FOLLOW_opt_func_head0 = {G.ID}
FOLLOW_sign = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FOLLOW_stat_block = {K.ELSE, S.SEMI_COLON}
FOLLOW_rel_expr = {S.CLOSE_PAR, S.SEMI_COLON, S.COMMA}
FOLLOW_variable = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.ASSIGN, S.CLOSE_PAR, O.MULT, O.AND, O.PLUS, S.COMMA, O.MINUS, O.DIV, O.EQ, O.GTE}
FOLLOW_factor = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.CLOSE_PAR, O.MULT, O.AND, O.PLUS, S.COMMA, O.MINUS, O.DIV, O.EQ, O.GTE}
FOLLOW_prog = {G.EOF}
FOLLOW_term = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.CLOSE_PAR, O.PLUS, S.COMMA, O.MINUS, O.EQ, O.GTE}
FOLLOW_mult_op = {L.FLOAT_LITERAL, S.OPEN_PAR, G.ID, O.PLUS, O.MINUS, L.INTEGER_LITERAL, O.NOT}
FOLLOW_rightrec_term = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.CLOSE_PAR, O.PLUS, S.COMMA, O.MINUS, O.EQ, O.GTE}
FOLLOW_rept_var_decl2 = {S.SEMI_COLON}
FOLLOW_opt_class_decl2 = {S.OPEN_CBR}
FOLLOW_rept_a_params1 = {S.CLOSE_PAR}
FOLLOW_expr = {S.CLOSE_PAR, S.SEMI_COLON, S.COMMA}
FOLLOW_idnest = {G.ID}
FOLLOW_rept_f_params_tail3 = {S.CLOSE_PAR, S.COMMA}
FOLLOW_function_call = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.CLOSE_PAR, O.MULT, O.AND, O.PLUS, S.COMMA, O.MINUS, O.DIV, O.EQ, O.GTE}
FOLLOW_rept_class_decl4 = {S.CLOSE_CBR}
FOLLOW_type = {K.LOCAL, G.ID, S.SEMI_COLON, K.DO}
FOLLOW_arith_expr = {O.LTE, O.GT, O.NEQ, O.LT, S.CLOSE_PAR, S.SEMI_COLON, S.COMMA, S.CLOSE_SBR, O.EQ, O.GTE}
FOLLOW_rept_f_params2 = {S.CLOSE_PAR, S.COMMA}
FOLLOW_rightrec_arith_expr = {O.LTE, O.GT, O.NEQ, O.LT, S.CLOSE_PAR, S.SEMI_COLON, S.COMMA, S.CLOSE_SBR, O.EQ, O.GTE}
FOLLOW_rept_f_params3 = {S.CLOSE_PAR}
FOLLOW_array_size = {S.CLOSE_PAR, S.OPEN_SBR, S.SEMI_COLON, S.COMMA}
FOLLOW_assign_stat = {S.SEMI_COLON}
FOLLOW_opt_func_body0 = {K.DO}
FOLLOW_rept_func_body2 = {K.END}
FOLLOW_rept_stat_block1 = {K.END}
FOLLOW_rept_variable0 = {G.ID}
FOLLOW_rept_prog0 = {G.ID, K.MAIN}
FOLLOW_rept_variable2 = {O.LTE, O.GT, O.NEQ, O.LT, O.OR, S.SEMI_COLON, S.CLOSE_SBR, S.ASSIGN, S.CLOSE_PAR, O.MULT, O.AND, O.PLUS, S.COMMA, O.MINUS, O.DIV, O.EQ, O.GTE}
FOLLOW_rept_prog1 = {K.MAIN}

FF_statement = FOLLOW_statement.union(FIRST_statement)
FF_rept_opt_class_decl22 = FOLLOW_rept_opt_class_decl22.union(FIRST_rept_opt_class_decl22)
FF_rept_indice = FOLLOW_rept_indice.union(FIRST_rept_indice)
FF_rept_function_call0 = FOLLOW_rept_function_call0.union(FIRST_rept_function_call0)
FF_add_op = FOLLOW_add_op.union(FIRST_add_op)
FF_rept_opt_func_body01 = FOLLOW_rept_opt_func_body01.union(FIRST_rept_opt_func_body01)
FF_visibility = FOLLOW_visibility.union(FIRST_visibility)
FF_START = FOLLOW_START.union(FIRST_START)
FF_func_head = FOLLOW_func_head.union(FIRST_func_head)
FF_func_def = FOLLOW_func_def.union(FIRST_func_def)
FF_a_params_tail = FOLLOW_a_params_tail.union(FIRST_a_params_tail)
FF_func_decl = FOLLOW_func_decl.union(FIRST_func_decl)
FF_var_decl = FOLLOW_var_decl.union(FIRST_var_decl)
FF_f_params_tail = FOLLOW_f_params_tail.union(FIRST_f_params_tail)
FF_member_decl = FOLLOW_member_decl.union(FIRST_member_decl)
FF_a_params = FOLLOW_a_params.union(FIRST_a_params)
FF_class_decl = FOLLOW_class_decl.union(FIRST_class_decl)
FF_f_params = FOLLOW_f_params.union(FIRST_f_params)
FF_rel_op = FOLLOW_rel_op.union(FIRST_rel_op)
FF_indice = FOLLOW_indice.union(FIRST_indice)
FF_func_body = FOLLOW_func_body.union(FIRST_func_body)
FF_opt_func_head0 = FOLLOW_opt_func_head0.union(FIRST_opt_func_head0)
FF_sign = FOLLOW_sign.union(FIRST_sign)
FF_stat_block = FOLLOW_stat_block.union(FIRST_stat_block)
FF_rel_expr = FOLLOW_rel_expr.union(FIRST_rel_expr)
FF_variable = FOLLOW_variable.union(FIRST_variable)
FF_factor = FOLLOW_factor.union(FIRST_factor)
FF_prog = FOLLOW_prog.union(FIRST_prog)
FF_term = FOLLOW_term.union(FIRST_term)
FF_mult_op = FOLLOW_mult_op.union(FIRST_mult_op)
FF_rightrec_term = FOLLOW_rightrec_term.union(FIRST_rightrec_term)
FF_rept_var_decl2 = FOLLOW_rept_var_decl2.union(FIRST_rept_var_decl2)
FF_opt_class_decl2 = FOLLOW_opt_class_decl2.union(FIRST_opt_class_decl2)
FF_rept_a_params1 = FOLLOW_rept_a_params1.union(FIRST_rept_a_params1)
FF_expr = FOLLOW_expr.union(FIRST_expr)
FF_idnest = FOLLOW_idnest.union(FIRST_idnest)
FF_rept_f_params_tail3 = FOLLOW_rept_f_params_tail3.union(FIRST_rept_f_params_tail3)
FF_function_call = FOLLOW_function_call.union(FIRST_function_call)
FF_rept_class_decl4 = FOLLOW_rept_class_decl4.union(FIRST_rept_class_decl4)
FF_type = FOLLOW_type.union(FIRST_type)
FF_arith_expr = FOLLOW_arith_expr.union(FIRST_arith_expr)
FF_rept_f_params2 = FOLLOW_rept_f_params2.union(FIRST_rept_f_params2)
FF_rightrec_arith_expr = FOLLOW_rightrec_arith_expr.union(FIRST_rightrec_arith_expr)
FF_rept_f_params3 = FOLLOW_rept_f_params3.union(FIRST_rept_f_params3)
FF_array_size = FOLLOW_array_size.union(FIRST_array_size)
FF_assign_stat = FOLLOW_assign_stat.union(FIRST_assign_stat)
FF_opt_func_body0 = FOLLOW_opt_func_body0.union(FIRST_opt_func_body0)
FF_rept_func_body2 = FOLLOW_rept_func_body2.union(FIRST_rept_func_body2)
FF_rept_stat_block1 = FOLLOW_rept_stat_block1.union(FIRST_rept_stat_block1)
FF_rept_variable0 = FOLLOW_rept_variable0.union(FIRST_rept_variable0)
FF_rept_prog0 = FOLLOW_rept_prog0.union(FIRST_rept_prog0)
FF_rept_variable2 = FOLLOW_rept_variable2.union(FIRST_rept_variable2)
FF_rept_prog1 = FOLLOW_rept_prog1.union(FIRST_rept_prog1)

FIRST_nested_array_size = {L.INTEGER_LITERAL, S.CLOSE_SBR}
FF_nested_array_size = FOLLOW_array_size.union(FIRST_nested_array_size)